name: Build, Release and Publish Python package to PyPI or TestPyPI

on:
  workflow_dispatch:
    inputs:
      pypienv:
        description: 'PyPi Environment'
        required: true
        default: 'Disabled'
        type: choice
        options:
        - Disabled
        - TestPyPi
        - PyPi

permissions:
  contents: write   # Required to create a GH release

jobs:
  build:
    name: Build distribution package
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
      with:
        persist-credentials: false
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.8"
    - name: Install pypa/build
      run: >-
        python3 -m
        pip install
        build
        --user
    - name: Generate variables
      run: |
        echo "SHORT_SHA=$(git rev-parse --short $GITHUB_SHA)" >> "$GITHUB_ENV"
    - name: Update README.md for TestPyPi
      if: inputs.pypienv == 'TestPyPi'
      run: |
        sed -i "s+pip install ps5-updates+pip install -i https://test.pypi.org/simple/ ps5-updates+g" README.md
        sed -i "s+](src/+](https://github.com/$GITHUB_REPOSITORY/blob/$GITHUB_SHA/src/+g" README.md
        sed -i "s+https://github.com/andshrew/PS4-Updates-Python+https://test.pypi.org/project/ps4-updates/+g" README.md
    - name: Update README.md for PyPi
      if: inputs.pypienv == 'PyPi'
      run: |
        sed -i "s+](src/+](https://github.com/$GITHUB_REPOSITORY/blob/$GITHUB_SHA/src/+g" README.md
        sed -i "s+https://github.com/andshrew/PS4-Updates-Python+https://pypi.org/project/ps4-updates/+g" README.md
    - name: Update demo.py for release
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        sed -i "s+release_version = None+release_version = '(${{ github.ref_name }}/${{ env.SHORT_SHA }})'+g" src/demo.py
    - name: Build a binary wheel and a source tarball
      run: python3 -m build
    - name: Store the distribution packages
      uses: actions/upload-artifact@v5
      with:
        name: python-package-distributions
        path: dist/
    - name: Create a draft release
      if: startsWith(github.ref, 'refs/tags/')
      env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        whl_name=`ls dist/*.whl | awk -F'/' '{print $NF}'`
        gh release create ${{ github.ref_name }} --generate-notes --verify-tag --draft
        gh release upload ${{ github.ref_name }} dist/$whl_name#$whl_name
        gh release upload ${{ github.ref_name }} src/demo.py#demo.py

  publish-to-pypi:
    name: Publish Python distribution package to PyPI
    if: inputs.pypienv == 'PyPi' && startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
    needs:
    - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/ps5-updates  # Replace <package-name> with your PyPI project name
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v6
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish distribution package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1

  publish-to-testpypi:
    name: Publish Python distribution package to TestPyPI
    if: inputs.pypienv == 'TestPyPi'
    needs:
    - build
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/ps5-updates

    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v6
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish distribution package to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/